/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.examples.schema.registry;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KafkaExampleMessage extends org.apache.avro.specific.SpecificRecordBase implements
    org.apache.avro.specific.SpecificRecord {

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"KafkaExampleMessage\",\"namespace\":\"kafka.examples.schema.registry\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}");
  private static final long serialVersionUID = 275949937053309365L;
  private static SpecificData MODEL$ = new SpecificData();
  private static final BinaryMessageEncoder<KafkaExampleMessage> ENCODER = new BinaryMessageEncoder<KafkaExampleMessage>(
      MODEL$, SCHEMA$);
  private static final BinaryMessageDecoder<KafkaExampleMessage> DECODER = new BinaryMessageDecoder<KafkaExampleMessage>(
      MODEL$, SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KafkaExampleMessage> WRITER$ = (org.apache.avro.io.DatumWriter<KafkaExampleMessage>) MODEL$
      .createDatumWriter(SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KafkaExampleMessage> READER$ = (org.apache.avro.io.DatumReader<KafkaExampleMessage>) MODEL$
      .createDatumReader(SCHEMA$);
  @Deprecated
  public java.lang.CharSequence f1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KafkaExampleMessage() {
  }

  /**
   * All-args constructor.
   *
   * @param f1 The new value for f1
   */
  public KafkaExampleMessage(java.lang.CharSequence f1) {
    this.f1 = f1;
  }

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<KafkaExampleMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<KafkaExampleMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KafkaExampleMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Deserializes a KafkaExampleMessage from a ByteBuffer.
   */
  public static KafkaExampleMessage fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /**
   * Creates a new KafkaExampleMessage RecordBuilder.
   *
   * @return A new KafkaExampleMessage RecordBuilder
   */
  public static kafka.examples.schema.registry.KafkaExampleMessage.Builder newBuilder() {
    return new kafka.examples.schema.registry.KafkaExampleMessage.Builder();
  }

  /**
   * Creates a new KafkaExampleMessage RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new KafkaExampleMessage RecordBuilder
   */
  public static kafka.examples.schema.registry.KafkaExampleMessage.Builder newBuilder(
      kafka.examples.schema.registry.KafkaExampleMessage.Builder other) {
    return new kafka.examples.schema.registry.KafkaExampleMessage.Builder(other);
  }

  /**
   * Creates a new KafkaExampleMessage RecordBuilder by copying an existing KafkaExampleMessage
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new KafkaExampleMessage RecordBuilder
   */
  public static kafka.examples.schema.registry.KafkaExampleMessage.Builder newBuilder(
      kafka.examples.schema.registry.KafkaExampleMessage other) {
    return new kafka.examples.schema.registry.KafkaExampleMessage.Builder(other);
  }

  /**
   * Serializes this KafkaExampleMessage to a ByteBuffer.
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return f1;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        f1 = (java.lang.CharSequence) value$;
        break;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   *
   * @return The value of the 'f1' field.
   */
  public java.lang.CharSequence getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   *
   * @param value the value to set.
   */
  public void setF1(java.lang.CharSequence value) {
    this.f1 = value;
  }

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  /**
   * RecordBuilder for KafkaExampleMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KafkaExampleMessage> implements
      org.apache.avro.data.RecordBuilder<KafkaExampleMessage> {

    private java.lang.CharSequence f1;

    /**
     * Creates a new Builder
     */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(kafka.examples.schema.registry.KafkaExampleMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing KafkaExampleMessage instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(kafka.examples.schema.registry.KafkaExampleMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Gets the value of the 'f1' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getF1() {
      return f1;
    }

    /**
     * Sets the value of the 'f1' field.
     *
     * @param value The value of 'f1'.
     * @return This builder.
     */
    public kafka.examples.schema.registry.KafkaExampleMessage.Builder setF1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'f1' field has been set.
     *
     * @return True if the 'f1' field has been set, false otherwise.
     */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'f1' field.
     *
     * @return This builder.
     */
    public kafka.examples.schema.registry.KafkaExampleMessage.Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KafkaExampleMessage build() {
      try {
        KafkaExampleMessage record = new KafkaExampleMessage();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

}
